name : CI pipeline

on : 
  push :
    branches:
       - main
jobs:
  build:
    runs-on : ubuntu-latest
    
    steps:
     - name : Checkout code
       uses : actions/checkout@v2
     - name : Buid the docker image
       run : docker build -t myImg .