name : CI pipeline

on : 
  push :
    branches:
       - main
jobs:
  build:
    runs-on : ubuntu-latest
    
    steps:
     - name : Checkout code
       uses : actions/checkout@v2
     - name : Build the docker image
       run : docker build -t ${{secrets.DOCKER_USERNAME}}/img .
     - name : Login to Docker Hub
       run : echo ${{secrets.DOCKER_PASSWORD}} | docker login -u ${{secrets.DOCKER_USERNAME}} --password--stdin
     - name : Push the img to Docker Hub
       run : docker push ${{secrets.DOCKER_USERNAME}}/img